# Generated by Django 4.2.6 on 2023-12-18 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Şehirler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('şehir', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Devlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ülke', models.CharField(max_length=100)),
                ('başkent', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('şehir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queryapp.şehirler')),
            ],
        ),
    ]
