# Generated by Django 4.2.6 on 2023-12-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0003_alter_devlet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devlet',
            name='şehir',
        ),
        migrations.AddField(
            model_name='devlet',
            name='şehir',
            field=models.ManyToManyField(to='queryapp.şehirler'),
        ),
    ]
